### ISSUE TITLE
Babel!

### ISSUE THREAD

**Issue by deebloo** [deebloo/generator-angular-blueprint#12]

**Comment by jamiebuilds** [comment]
Hi @deebloo, Babel contributor here, if you need any help getting setup let me know here or ask in our support chat: https://gitter.im/babel/babel

**Comment by deebloo** [comment]
Thanks man. I have a angular app up and running using babel but still have a bit to go before it's something I'll update in the generator. I'll certainly check up if I have any issues.

**Comment by jamiebuilds** [comment]
Sweet

**Comment by deebloo** [comment]
first go at it is in branch es6. build seems to be working, need to see if code styles are best and update the prod build

**Comment by deebloo** [comment]
@thejameskyle working on the base app structure before moving into the generator. All of the unit tests pass, the app runs and builds (other then the issue below)
The only issue I am having is getting the compiled template cache to work. (but I think this is a browserify issue rather then a babel issue).
I also have several auto injectors set up to automatically attach the generated code to the angular app. (in the index.js file under each man directory under client/app)

https://github.com/deebloo/angular-blueprint/tree/es6

**Comment by deebloo** [comment]
@thejameskyle do you know of any good jsdocs alternatives that work with ES6?

**Comment by jamiebuilds** [comment]
Right now I think dox works the best just because it is regex based and doesn't pay attention to the rest of the code at all. Although there needs to be a better jsdoc system in the future which can take advantage of ES6+.

**Comment by deebloo** [comment]
@thejameskyle thanks ill look into it. docs is the last step. I have everything else working in the seed project.

**Comment by deebloo** [comment]
Hey so its been a while since this issue started. BUT. the current master branch is up and running with either ES5 or ES6 code via Babel

**Comment by Nevraeka** [comment]
woot woot! I can't wait to start using it at work @deebloo

**Comment by jamiebuilds** [comment]
Nice!
