### ISSUE TITLE
Injector error serving the build

### ISSUE THREAD

**Issue by arelstone** [deebloo/generator-angular-blueprint#24]
I've followed the steps in then readme file.

When i run 

> npm run build

The build process returns no errors

```
Done, without errors.

Execution Time (2016-08-19 11:36:05 UTC+2)
concurrent:dist    2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 15%
ngAnnotate:dist   579ms  ▇▇▇▇▇▇▇▇▇ 4%
cdnify:dist        4.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 30%
cssmin:generated  635ms  ▇▇▇▇▇▇▇▇▇ 4%
uglify:generated   6.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 42%
jsdoc:client      413ms  ▇▇▇▇▇▇ 3%
Total 14.9s
```

When i cd into 

> dist/client 

and then run 

> http-server or php -S localhost:8080 

i get the error below

> vendor.f741b618.js:1 Uncaught Error: [$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
> http://errors.angularjs.org/1.5.8/$injector/nomod?p0=myApp

Has anyone have the same problem. Does anyone know how to fix this?

**Comment by deebloo** [comment]
@arelstone Can you let me know.
1. OS
2. node version
3. npm version
4. angular-blueprint version

**Comment by arelstone** [comment]
Mac OsX El Capitan 10.116
Node version: 5.6.0
NPM verison: 3.6.0
ES5 version of the generator

**Comment by arelstone** [comment]
I've tried adding AppCtrl.$inject = ['$rootScope']; to the application.controller.js file. Still gets the same error

**Comment by mastuart** [comment]
Hey @deebloo! Any update on this? I'm getting the same thing.

**Comment by deebloo** [comment]
hey @mastuart and @arelstone so sorry for the super long delay. I haven't had a lot of time to devote to my own open source stuff recently. I know the es5 templates are using very old deps and in general may be out of date. If you all want to take a crack at updating it I would be happy to review a PR

**Comment by deebloo** [comment]
Issue should be fixed with a or that was just merged. Will release soon
